name: dart_dashboard_backend_ont_v1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.2+1
  build_runner: ^2.4.15
  dart_jsonwebtoken: ^3.2.0
  objectbox: ^4.2.0
  objectbox_generator: ^4.2.0
  postgres: ^3.5.6
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
